name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: pnpm install --frozen-lockfile

      - name: TypeScript
        run: pnpm ts

      - name: Lint
        run: pnpm lint

      - name: CSS Lint
        run: pnpm csslint
